name: Deploy Calculator App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Removed the Docker Buildx setup step as requested

      - name: Build Docker image
        run: sudo docker build -t calculator-app .

      - name: Stop and remove old container
        run: |
          docker stop calculator-container || true
          docker rm calculator-container || true

      - name: Run new container
        run: |
          docker run -d -p 80:5000 --name calculator-container calculator-app
